title: SDR - Software DevelopeR
description: sharing seputar Software Developer
author: SuDiRman
email: mdsudirman@gmail.com
theme: minima

header_pages:
    - index.md
    - page2.md
    - about.md
    # ... halaman lain Anda

# Plugins
plugins:
    - jekyll-feed
    - jekyll-seo-tag

# Exclude files
exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor

# Sass
sass:
    sass_dir: _sass
    style: compressed

google_analytics: G-DD3C3FZW9H

defaults:
    - scope:
          path: '_posts/id'
          type: posts
      values:
          lang: id
          permalink: /id/:title/
          layout: post
    - scope:
          path: '_posts/en'
          type: posts
      values:
          lang: en
          permalink: /en/:title/
          layout: post
